Increment-9
amphiphile/urlshortener pull request #2
Opened 2024-07-02 15:10 UTC by amphiphile

Результаты спринта 2

2024-07-02 16:55 UTC, Perederey requested changes
Отличная работа, видно, что ты вложила много усилий! Но есть пару замечаний:
- Обрати внимание на использование `gin.Default()` вместо ручного добавления middleware, это упростит твой код и уберет дублирование.
- Также стоит добавить модульности проекту, это поможет проще управлять зависимостями 
В целом, прогресс супер, так держать! 🚀

2024-07-02 16:55 UTC, Perederey commented on cmd/shortener/main.go
> -	router := gin.Default()
gin.Default() уже включает gin.Recovery(), вместо использования gin.New() и ручного добавления справочников

2024-07-02 16:55 UTC, Perederey commented on internal/logger/logger.go
> +func Middleware() gin.HandlerFunc {
Для большей гибкости и тестируемости можно добавить интерфейс для логгера и использовать его вместо конкретной реализации в middleware. Например: ```go
type Logger interface {
	Info(msg string, fields ...zap.Field)
}
'''

2024-07-02 16:55 UTC, Perederey commented on cmd/shortener/config.go
>  	ServerAddress string
Поле ServerAddress лучше назвать Address для соответствия общей структуре именования

2024-07-02 16:55 UTC, Perederey commented on cmd/shortener/main.go
URLHandler лучше переименовать в URLService, т.к. это не обработчик, а сервис

2024-07-02 16:55 UTC, Perederey commented on cmd/shortener/main_test.go
> @@ -114,3 +118,39 @@
Имя TestGzipCompression не отражает полноту проверки, лучше переименовать в TestShrinkAndUnwrapGzip

2024-07-02 16:55 UTC, Perederey commented on cmd/shortener/main_test.go
> +
Хотелось бы увидеть больше тестов и проверок assert внутри

2024-07-02 16:55 UTC, Perederey commented on cmd/shortener/main_test.go
>  import (
Тесты для Main не принято делать.

Лучше разнеси проект на части, и сделай модули (пакеты)

Для того посмотри вебинары по архитектуре, которые мы давали

2024-07-05 21:42 UTC, amphiphile commented on cmd/shortener/main.go
> -	router := gin.Default()
Честно говоря, использовала gin.New(), чтобы не дублировать использование по умолчанию gin.Logger()

2024-07-05 21:42 UTC, amphiphile commented on internal/logger/logger.go
> +func Middleware() gin.HandlerFunc {
Переписала

2024-07-05 21:43 UTC, amphiphile commented on cmd/shortener/main_test.go
> +
Sorry... fixed

2024-07-05 21:52 UTC, amphiphile commented on cmd/shortener/main_test.go
>  import (
В каком пакете лучше разместить такие тесты? Хочу протестировать сервер целиком, как черный ящик

2024-07-06 09:39 UTC, Perederey commented on cmd/shortener/main.go
> -	router := gin.Default()
можно, да, кстати

2024-07-06 09:40 UTC, Perederey commented on cmd/shortener/main_test.go
>  import (
в целом можно, но тогда нужно тестировать e2e - и лучше тогда отдельно положить тесты в e2e например за internal папку

2024-07-06 09:40 UTC, Perederey approved these changes
стало еще лучше!

2024-07-07 14:17 UTC, merged